config/routes.rb
Beers::Application.routes.draw do
  
  get "home/index"
  
  resources :home, :beers, :sessions
  
  resources :my_beers do
    collection do
      get :add      
    end    
  end
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  root :to => 'home#index'
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  has_many :my_beers  
  attr_accessible :name

  def self.search(search)
    if search
      where(["name LIKE ?", "%#{search}%"])
    else
      all
    end
  end

end

app/models/my_beer.rb
class MyBeer < ActiveRecord::Base
  belongs_to :beer
  
  attr_accessible :user_id, :beer_id
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
  
  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
    block_given? ? yield(@facebook) : @facebook
  rescue Koala::Facebook::APIError => e
    logger.info e.to_s
    nil # or consider a custom null object
  end
  
  def picture
    facebook.get_picture("me", :type => "normal")
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in
    unless current_user
      redirect_to new_session_path
    end
  end
  helper_method :current_user, :logged_in
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  before_filter :logged_in

  def index
    @beers = Beer.search(params[:search])
  end

  def new
    @beer = Beer.new
  end
  
  def create
    @beer = Beer.new(params[:beer])
    if @beer.save
      redirect_to new_beer_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :logged_in
  
  def index
    @mybeers = MyBeer.where(["user_id = ?", current_user.uid])
  end
end

app/controllers/my_beers_controller.rb
class MyBeersController < ApplicationController

  before_filter :logged_in

  def add
    my_beer = MyBeer.new(:user_id => params[:user_id], :beer_id => params[:beer_id])
    if my_beer.save
      redirect_to root_path
    end
  end
  
  def destroy
    get_my_beer = MyBeer.find(params[:id])
    get_my_beer.destroy
    redirect_to root_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    respond_to do |format|
      format.html { render :layout => "login" }
    end
  end
  
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def count_my_beers
    MyBeer.where(["user_id = ?", current_user.uid]).size
  end
  
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_beers_helper.rb
module MyBeersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/beers/index.html.erb
<% @beers.each do |beer| %>
	
	<div id="each_beer" onmouseover="GetMyBeer(<%= beer.id %>)" onmouseout="HideGetMyBeer(<%= beer.id %>)">
		<%= image_tag("garrafa.png", :width => "76") %>
		<div class="get_beer" id="<%= beer.id %>" style="display: none">
			<%= link_to image_tag("ok.png"), add_my_beers_path(:user_id => current_user.uid, :beer_id => beer.id) %>
		</div>
		<p><%= beer.name %></p>
	</div>
	
<% end %>

app/views/beers/new.html.erb
<%= form_for(@beer) do |f| %>
	
	<%= f.text_field :name %>
	<%= f.submit %>
	
<% end %>

app/views/home/index.html.erb
<% if @mybeers.blank? %>
	<div id="start">
		<p>uma cerveja?</p>
		<span>inicie procurando uma cerveja:</span>
		<%= form_tag beers_path, :method => :get do %>
			<%= text_field_tag :search, params[:search] %>
			<%= image_submit_tag("lupa.png", :name => nil, :width => "15", :class => "lupa") %>
		<% end %>
	</div>
<% end %>

<% @mybeers.each do |my| %>

	<div id="each_beer">
		<%= image_tag("garrafa2.png", :width => "76") %>
		<p><%= my.beer.name %></p> <%#= link_to "remover", my, :method => "delete" %>
	</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Beers</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		
		<div id="nav_top">
			<div id="nav_top_in">
				<div id="nav_top_search">
					<%= form_tag beers_path, :method => :get do %>
						<%= text_field_tag :search, params[:search] %>
						<%= image_submit_tag("lupa.png", :name => nil, :width => "15", :class => "lupa") %>
					<% end %>
				</div>
				<div id="nav_top_links">
					<%= link_to "Minhas Cervejas", root_path %> .
					<%= link_to "Lista de Cervejas", :beers %> .
					<%= link_to "Sair", signout_path, id: "sign_out" %>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		
		<div id="content">
			<div id="facebook">
				<div id="facebook_pic">
					<%#= image_tag("#{current_user.picture}", :width => "60") %>
				</div>
				<div id="facebook_name">
					<%= current_user.name	%><br />
				</div>
				<div id="count_my_beers">
					<%= pluralize(count_my_beers, "Cerveja") %>
				</div>
				<div class="clear"></div>
			</div>
			
			<div id="top_armario"></div>
			<div id="show_my_beers">
				<%= yield %>
				<div class="clear"></div>
			</div>

			
		</div>

	</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Beers</title>
	  <%= stylesheet_link_tag    "login", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		
		<div id="header_login">
			<div id="header_login_in">
				<div id="beers_image_left">
					<%= image_tag("beers.png") %>
				</div>
				
				<div id="text_right">
					<h1>Colecione e Compartilhe cada cerveja que você já bebeu!</h1>
					<br />
					<p>Basta fazer login com sua conta do facebook e começar a usar e compartilhar!</p>
					
					<br />
					<br />
					<br />
					<br />
					
					<%= yield %>
				</div>
				<div class="clear"></div>
			</div>
		</div>

	</body>
</html>